//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingService
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelRooms
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortDescription { get; set; }
        public string FullDescription { get; set; }
        public string ImagePath { get; set; }
        public string Category { get; set; }
        public double Rating { get; set; }
        public double Price { get; set; }
        public int NumberOfBeds { get; set; }
        public bool IsAvailable { get; set; }
        public string Amenities { get; set; }
        public int Stars { get; set; }
        public bool HasBalcony { get; set; }
        public bool IsNonSmoking { get; set; }
    }
}
