CREATE TABLESPACE hotel_db_data
DATAFILE 'D:\4sem\course-work\hotel_data01.dbf' SIZE 500M AUTOEXTEND ON NEXT 100M MAXSIZE 2G;

CREATE TEMPORARY TABLESPACE hotel_db_temp
TEMPFILE 'D:\4sem\course-work\hotel_temp01.dbf' SIZE 200M AUTOEXTEND ON NEXT 50M MAXSIZE 500M;