ALTER SESSION SET "_oracle_script" = TRUE;
CREATE TABLESPACE TS_KEI
    DATAFILE 'D:\4sem\db\lab2\TS_KEI.dbf'
    SIZE 7 m
    AUTOEXTEND ON NEXT 5M
    MAXSIZE 30M
    EXTENT MANAGEMENT LOCAL;
    
CREATE TEMPORARY TABLESPACE TS_KEI_TEMP
    TEMPFILE 'D:\4sem\db\lab2\TS_KEI_TEMP.dbf'
    SIZE 5 m
    AUTOEXTEND ON NEXT 3M
    MAXSIZE 20M
    EXTENT MANAGEMENT LOCAL;
    
SELECT TABLESPACE_NAME, STATUS FROM SYS.DBA_TABLESPACES;

SELECT FILE_NAME, TABLESPACE_NAME, STATUS FROM DBA_DATA_FILES
UNION
SELECT FILE_NAME, TABLESPACE_NAME, STATUS FROM DBA_TEMP_FILES

CREATE ROLE RL_KEICORE;
GRANT CREATE SESSION,
    CREATE TABLE,
    CREATE VIEW,
    CREATE ANY PROCEDURE TO RL_KEICORE;
    
SELECT * FROM DBA_ROLES WHERE ROLE LIKE 'RL%';
SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'RL_KEICORE';

CREATE PROFILE PF_KEICORE LIMIT
FAILED_LOGIN_ATTEMPTS 5
PASSWORD_LIFE_TIME 30
PASSWORD_REUSE_TIME 365
PASSWORD_REUSE_MAX 10
PASSWORD_LOCK_TIME 1
PASSWORD_GRACE_TIME 7;

SELECT PROFILE FROM DBA_PROFILES;

SELECT RESOURCE_NAME, LIMIT FROM DBA_PROFILES WHERE PROFILE = 'PF_KEICORE';

SELECT RESOURCE_NAME, LIMIT FROM DBA_PROFILES WHERE PROFILE = 'DEFAULT';

CREATE USER KEICORE
IDENTIFIED BY QWE123QWE
DEFAULT TABLESPACE TS_KEI
TEMPORARY TABLESPACE TS_KEI_TEMP
PROFILE PF_KEICORE
ACCOUNT UNLOCK
PASSWORD EXPIRE;

DROP USER KEICORE
GRANT RL_KEICORE TO KEICORE
ALTER USER KEICORE QUOTA 2M ON TS_KEI;

ALTER TABLESPACE TS_KEI OFFLINE;

SELECT * FROM KEI_T;

ALTER TABLESPACE TS_KEI ONLINE;
SELECT * FROM KEI_T;