SELECT PDB_NAME, STATUS FROM DBA_PDBS;
SELECT name, V$PDBS.OPEN_MODE FROM V$PDBS;

ALTER SESSION SET CONTAINER=KEI_PDB;

CREATE PLUGGABLE DATABASE KEI_PDB
ADMIN USER KEIADMIN IDENTIFIED BY 12345
ROLES=(CONNECT, RESOURCE)
FILE_NAME_CONVERT = ('D:\OKAKL.DB\ORCL\PDBSEED\', 'D:\OKAKL.DB\ORCL\KEI_PDB\');

SELECT PDB_NAME, STATUS FROM DBA_PDBS;

CREATE TABLESPACE TS_KEI_DATA
DATAFILE 'D:\4sem\db\lab3\TS_KEI_DATA.dbf'
SIZE 2M AUTOEXTEND ON
NEXT 1M
MAXSIZE 5M;

CREATE TABLESPACE TS_KEI_PDB_TEMP
DATAFILE 'D:\4sem\db\lab3\TS_KEI_PDB_TEMP.dbf'
SIZE 2M AUTOEXTEND ON
NEXT 2M
MAXSIZE 5M;

CREATE ROLE RL_KEI_PDB;
GRANT CREATE SESSION,
    CREATE TABLE,
    CREATE VIEW,
    CREATE PROCEDURE
    TO RL_KEI_PDB;
    
CREATE PROFILE PF_KEI_PDB LIMIT
PASSWORD_LIFE_TIME 180
SESSIONS_PER_USER 3
FAILED_LOGIN_ATTEMPTS 7
PASSWORD_LOCK_TIME 1
PASSWORD_REUSE_TIME 10
PASSWORD_GRACE_TIME DEFAULT
CONNECT_TIME 180
IDLE_TIME 30;

CREATE USER U1_KEI_PDB IDENTIFIED BY 12345
DEFAULT TABLESPACE TS_KEI_DATA QUOTA UNLIMITED ON TS_KEI_DATA
PROFILE PF_KEI_PDB
ACCOUNT UNLOCK

GRANT RL_KEI_PDB TO U1_KEI_PDB

CREATE TABLE KEI_table (
    id NUMBER
);

INSERT INTO KEI_table VALUES (3);

SELECT * FROM KEI_table;

SELECT TABLESPACE_NAME, STATUS, CONTENTS FROM DBA_TABLESPACES;
SELECT FILE_NAME, TABLESPACE_NAME FROM DBA_TEMP_FILES;
SELECT ROLE, AUTHENTICATION_TYPE FROM DBA_ROLES;
SELECT * FROM DBA_PROFILES;
SELECT USERNAME, ACCOUNT_STATUS, DEFAULT_TABLESPACE, PROFILE FROM DBA_USERS;
SELECT GRANTEE AS USERNAME, GRANTED_ROLE FROM DBA_ROLE_PRIVS;

CREATE USER C##KEI IDENTIFIED BY 12345 CONTAINER=ALL;
GRANT CREATE SESSION TO C##KEI CONTAINER=ALL;
GRANT CREATE TABLE TO C##KEI CONTAINER=ALL;

CREATE TABLE test (id NUMBER);
insert into test values (1);
SELECT * FROM TEST;

SELECT * FROM USER_OBJECTS;

-- 12-13
CREATE USER C##SAA IDENTIFIED BY 123123 CONTAINER=ALL;
GRANT CREATE SESSION TO C##SAA CONTAINER=ALL;
