SELECT TABLESPACE_NAME, CONTENTS FROM DBA_TABLESPACES;

SELECT TABLESPACE_NAME, FILE_NAME FROM DBA_DATA_FILES
UNION ALL
SELECT TABLESPACE_NAME, FILE_NAME FROM DBA_TEMP_FILES;

SELECT * FROM V$LOGFILE;
SELECT * FROM V$LOG;
ALTER SYSTEM SWITCH LOGFILE;

ALTER DATABASE ADD LOGFILE GROUP 4 'D:\OKAKL.DB\ORCL\REDO04.LOG'
SIZE 50m BLOCKSIZE 512;

ALTER DATABASE ADD LOGFILE MEMBER 'D:\OKAKL.DB\ORCL\REDO041.LOG' TO GROUP 4;
ALTER DATABASE ADD LOGFILE MEMBER 'D:\OKAKL.DB\ORCL\REDO042.LOG' TO GROUP 4;
ALTER DATABASE ADD LOGFILE MEMBER 'D:\OKAKL.DB\ORCL\REDO043.LOG' TO GROUP 4;

ALTER DATABASE DROP LOGFILE MEMBER 'D:\OKAKL.DB\ORCL\REDO041.LOG';
ALTER DATABASE DROP LOGFILE MEMBER 'D:\OKAKL.DB\ORCL\REDO042.LOG';
ALTER DATABASE DROP LOGFILE MEMBER 'D:\OKAKL.DB\ORCL\REDO043.LOG';
ALTER DATABASE DROP LOGFILE GROUP 4;

SELECT INSTANCE_NAME, ARCHIVER, ACTIVE_STATE FROM V$INSTANCE;

ALTER SYSTEM SWITCH LOGFILE;
SELECT NAME, SEQUENCE#, FIRST_CHANGE#, NEXT_CHANGE# FROM V$ARCHIVED_LOG;

SELECT * FROM V$CONTROLFILE;
ALTER DATABASE BACKUP CONTROLFILE TO TRACE;