select * from dba_tablespaces;

CREATE TABLESPACE KEI_QDATA DATAFILE 'D:/4sem/db/KEI_QDATA.dbf' SIZE 10M OFFLINE;
ALTER TABLESPACE KEI_QDATA ONLINE;
ALTER USER KEICORE QUOTA 2M ON KEI_QDATA;

CREATE TABLE KEI_T1 (
    id NUMBER PRIMARY KEY,
    data VARCHAR2(100)
) TABLESPACE KEI_QDATA;
INSERT INTO KEI_T1 VALUES (1, 'Data 1');
INSERT INTO KEI_T1 VALUES (2, 'Data 2');
INSERT INTO KEI_T1 VALUES (3, 'Data 3');

SELECT * FROM DBA_SEGMENTS WHERE TABLESPACE_NAME = 'KEI_QDATA';

DROP TABLE KEI_T1;

SELECT * FROM USER_RECYCLEBIN;

FLASHBACK TABLE KEI_T1 TO BEFORE DROP;

BEGIN
    FOR i IN 1..10000 LOOP
        INSERT INTO KEI_T1 VALUES (i, 'Data ' || i);
    END LOOP;
    COMMIT;
END;

SELECT * FROM KEI_T1 WHERE ID = '10000';

SELECT * FROM DBA_EXTENTS;

SELECT ROWID, ID, COLUMN1, COLUMN2 FROM KEI_T;
SELECT ORA_ROWSCN, id, data FROM KEI_T1;

-- 14: https://torofimofu.blogspot.com/2016/12/orarowscn-oracle-11g.html
DROP TABLE KEI_T1;
CREATE TABLE KEI_T1 (
    id NUMBER PRIMARY KEY,
    data VARCHAR2(100)
) TABLESPACE KEI_QDATA rowdependencies;

UPDATE KEI_T1 SET DATA = 'Data 2 UPDATED' WHERE ID = 2;
COMMIT;

SELECT TABLE_NAME, DEPENDENCIES FROM USER_TABLES WHERE TABLE_NAME = 'KEI_T1';
